### ISSUE TITLE
运行提示语法错误

### ISSUE THREAD

**Issue by siming36** [tsinglinrain/WechatPay_to_Notion#1]
代码是直接从Github的Code里download的Zip。
不管是运行wechat2notion.py还是main.py，都提示
“ 
File "<stdin>", line 1
    /Users/hommy/Desktop/WechatPay_to_Notion-main/wechat2notion.py 
    ^
SyntaxError: invalid syntax
”
-----------------------------------------------------------------------------
wechat2notion代码：
import requests
import csv
import re

# 基本信息
database_id = "f"    # 数据库ID, 要填进去哦
token = "sec" # token, 记得自己填写
raw_path = "wechat_raw.csv"
new_path1 = "wechat_new1.csv"
new_path2 = "wechat_new2.csv"

def get_new_data(raw_path):
    """读取原始文件，截取并得到新的文件
    
    Args:
        raw_path (str): 原始文件路径

    Returns:
       new_path (str): 新的文件路径
    """

    with open(raw_path, encoding="utf-8", newline="") as f: # 注意这里的路径
        lines = f.readlines()   # 读取所有行
        for line in lines:  # 遍历每一行
            if line.startswith("----------------------微信"):   # 找到以"----------------------微信"开头的行
                # 将该行之后的所有行按照每一行写入新文件并且用re删除每一行中的空格
                with open(new_path1, "a", encoding="utf-8", newline="") as f2:
                    f2.writelines(re.sub(r"\s+,", ",", line) for line in lines[lines.index(line) + 1:])

def get_new_data2(new_path1, new_path2):
    """读取新的文件，得到最终的文件

    Args:
        new_path1 (str): 新的文件路径1
        new_path2 (str): 新的文件路径2
    """

    with open(new_path1, encoding="utf-8", newline="") as f:
            # 将每一列的数据读取到一个列表中
            csvreader = csv.reader(f)   # 读取csv文件,返回的是一个迭代器,每一行是一个列表
            for row in csvreader: # 打印测试一下
                if row[4] == "支出":  # 原来是因为有空格, 找了半天bug, 应当第一步就把空格删去
                    print(row[4], row[6], row[1], row[0])
                    with open(new_path2, "a", encoding="utf-8", newline="") as f:
                        csvwriter = csv.writer(f)
                        csvwriter.writerow(row)
                    # print("**")
                # print(row[0])

def in2notion(content, price, category, date, remarks=""):
    """将输入的内容转换为notion的格式
    
    Args:
        content (str): 名称
        price (float): 价格
        category (str): 类别
        date (str): 日期

    Returns:
        properties: 返回notion的格式
    """

    properties = {
        "Name": {
            "title": [
            {
                "text": {
                    "content": content
                }
            }  
            ]
        },
        "Price": {
            "number": price
        },
        "Category": {
            "select": {
                "name": category
            }
        },
        "Date": {
            "date": {
                "start": date,
                "time_zone": "Asia/Shanghai"    # 时区, 参见官方文档
            }
        },
        "From": {
            "select": {
                "name": "Wechat"
            }
        },
        "Remarks": {
            "rich_text": [
            {
                "text": {
                    "content": remarks
                }
            }
        ]
        }
    }
    return properties

# post请求
def post_notion(properties):
    """post请求
    
    Args:
        properties: 需要post的内容
        
    Returns:
        response: 返回response
    """

    url = "https://api.notion.com/v1/pages"
    payload = {
        "parent": {"database_id": database_id},
        "properties": properties,
        #"children": ["string"],    # 不需要children
        #"icon": "string",
        #"cover": "string"
    }
    headers = {
        "accept": "application/json",
        "Notion-Version": "2022-06-28", # 版本号
        "content-type": "application/json",
        "Authorization": "".join(["Bearer", " ", token]) # 注意空格, 之前没注意空格, 一直报错
    }
    response = requests.post(url, json=payload, headers=headers)
    return response

def result(response):
    """判断是否成功

    Args:
        response: 返回的response
    """

    if response.status_code == 200:
        print("成功...")
    else:
        print("失败...")
        print(response.text)

def get_data_col(new_path3):
    """读取data_new.csv文件
    
    Args:
        new_path3 (str): csv文件路径
        
    Returns:
        row: 返回每一行       
    """
    with open(new_path2, encoding="utf-8", newline="") as f:
        csvreader = csv.reader(f)   # 读取csv文件,返回的是一个迭代器,每一行是一个列表
        for row in csvreader:
            row_5 = float(row[5][1:]) # 价格需要转换为浮点数, 并且去掉前面的￥符号
            row_0 = "".join([row[0][:10], "T", row[0][11:], "Z"])  # 日期需要转换ISO 8601 format date
            if row[3].startswith("KFC"):# 如果row[3]以KFC开头, 则将row[3]的值改为KFC，并且写入remarks, 否则不写入remarks
                row_3 = "KFC"
                properties = in2notion(row_3, row_5, row[1], row_0, remarks=row[3])
            else:
                properties = in2notion(row[3], row_5, row[1], row_0, remarks="")
            response = post_notion(properties)
            result(response)

# 主函数
def main():
    get_new_data(raw_path)
    get_new_data2(new_path1, new_path2)
    get_data_col(new_path2)

if __name__ == "__main__":
    main()

**Comment by siming36** [comment]
使用Visual Studio Code运行，提示
“
{"object":"error","status":400,"code":"validation_error","message":"body failed validation: body.properties.Date.date.start should be a valid ISO 8601 date string, instead was `\"2023-04-21T15:02:19ZZ\"`."}
”

**Comment by siming36** [comment]
仔细看了一下，通过VC运行后，每条记录都会提示
“
{"object":"error","status":400,"code":"validation_error","message":"body failed validation: body.properties.Date.date.start should be a valid ISO 8601 date string, instead was `\"2023-04-21T15:02:19ZZ\"`."}
”
然后每条流水都能成功导入Notion，但每条流水都会重复导入9次，也就是说最终的结果就是只有44条流水的微信账单，导入notion后总共有360条。
<img width="978" alt="image" src="https://github.com/tsinglinrain/WechatPay_to_Notion/assets/131593250/c36b6fa7-86cd-47f6-8439-2e94838462e7">
![image](https://github.com/tsinglinrain/WechatPay_to_Notion/assets/131593250/553d1330-6f15-40be-a288-f8fe61106e90)

**Comment by tsinglinrain** [comment]
代码并无问题。我以为是时间问题。但是我看了一下说明文档，并不是。

![image](https://github.com/tsinglinrain/WechatPay_to_Notion/assets/68103537/0d3edd57-ec53-49b8-b9bf-19b1119fb2ef)

我希望你可以删除所有，然后重新运行。

**Comment by siming36** [comment]
删掉之前的文件，重新解压zip后，可以正常导入了，感谢感谢~
但是总共有44条流水，只成功导入了40条，会是什么问题咧？

**Comment by tsinglinrain** [comment]
请查看报错提示。对于这一点，我的代码不够完善，我也不清楚。

**Comment by siming36** [comment]
好的，我再仔细看看，非常感谢哈~

**Comment by tsinglinrain** [comment]
不客气。还有什么其他问题可以继续提问。如果不介意，可以把运行后的整个文件夹压缩后发给我看看。这个代码我个人一直在使用，已经用了三个月了，一直没有问题。介意就算了，毕竟是隐私。

另外你的`toke`和`id`最好别泄露出去，注意个人信息保护。

**Comment by siming36** [comment]
Token的问题感谢提醒，后面测试好了我再统一更换就好。
文件夹压缩怎么发给你？留个您的邮箱给我哈。

**Comment by siming36** [comment]
另外我是个python小白，如果需要导入csv的所有信息，如何操作？
特别是我看代码，不是很清楚如何从csv全量数据中，只抽取了其中几个字段，是在哪段代码上提现滴？

**Comment by siming36** [comment]
看到了，是不是这一段？
with open(new_path1, encoding="utf-8", newline="") as f:
            # 将每一列的数据读取到一个列表中
            csvreader = csv.reader(f)   # 读取csv文件,返回的是一个迭代器,每一行是一个列表
            for row in csvreader: # 打印测试一下
                if row[4] == "支出":  # 原来是因为有空格, 找了半天bug, 应当第一步就把空格删去
                    print(row[4], row[6], row[1], row[0])
                    with open(new_path2, "a", encoding="utf-8", newline="") as f:
                        csvwriter = csv.writer(f)
                        csvwriter.writerow(row)
                    # print("**")
                # print(row[0])

**Comment by tsinglinrain** [comment]
然后，ummmm，知乎那边太懒了，没修改更新，(别看知乎，我用空更一下知乎吧)。恳请你**不要再用**`notion_property.py`，那个已经**作废**了。我一个小时前更了一下项目给删了，**以后再也没人使用啦**。


建议你重新下载新的项目代码压缩包，然后按照github上的README说明继续操作。

我觉得新版代码没问题，如果还是出现问题可以将运行后的文件夹压缩之后发给我看看。我的邮箱为l3071635955@163.com

我把之前的代码拆开了就是为了便于自行修改。自定义仅需要修改`get_need_data.py`和`notion_property.py`，然后在Notion Database把properties设置好，这样一来，就很方便了。不过新手可能有点困难。如果想改，需要查阅官方文档以及一定的python知识，最好是学一下pandas这个库。（我自己一开始想用pandas，但是不熟练就没用，下次有空更新还是想用这个，也会增加代码可读性，下次出个教程）当然也可以问问chatgpt，帮助写一下代码。

其实如果你需要全部账单的导入，我建议直接将账单改成标准csv格式，如下面两张图，然后直接**在Notion那边导入**。**不用敲代码**。

代码就是因为向自定义而作的。比如你在旧版本的`notion_property.py`中有关于肯德基的自定义，就是因为默认给出一长串，我只想要`KFC`，于是需要利用代码修改。（新版没有加上去，因为懒）
![image](https://github.com/tsinglinrain/WechatPay_to_Notion/assets/68103537/09458f36-8f8f-4a73-87e7-cbee5564c5ed)
![image](https://github.com/tsinglinrain/WechatPay_to_Notion/assets/68103537/32e8b09d-4e8e-4e7a-ac3a-5541b8126da2)

**Comment by siming36** [comment]
好滴，刚想问你代码里面的KFC是啥，哈哈~
我重新下载试试看。

**Comment by siming36** [comment]
新的main，运行后提示。TypeError: notion_property() missing 1 required positional argument: 'remarks'

**Comment by tsinglinrain** [comment]
没问题啊。我这边运行不报错。

**Comment by siming36** [comment]
运行正常了，非常感谢！

还有个小问题。我想把账单里的“交易对方”加入notion，我先在notion上增加了一个叫Saler的text字段，然后修改了get_need_data.py，见下文，无法正常导入，可以帮忙看看具体是什么问题吗？

def notion_property(content, price, category, date, remarks, saler=""):
    """将输入的内容转换为notion的格式
    
    Args:
        content (str): 名称
        price (float): 价格
        category (str): 类别
        date (str): 日期
        saler(str): 商家

    Returns:
        properties: 返回notion的格式
    """

    properties = {
        "Name": {
            "title": [
            {
                "text": {
                    "content": content
                }
            }  
            ]
        },
        "Price": {
            "number": price
        },
        "Category": {
            "select": {
                "name": category
            }
        },
        "Date": {
            "date": {
                "start": date,
                "time_zone": "Asia/Shanghai"    # 时区, 参见官方文档
            }
        },
        "From": {
            "select": {
                "name": "Wechat"
            }
        },
        "Saler": {
            "rich_text": [
            {
                "text": {
                    "content": saler
                }
            }
        ]
        }
    }
    return properties

**Comment by linlithgowshire** [comment]
提示这个错误，是哪里操作不对吗？
File "/Users/linlithgowshire/Downloads/WechatPay_to_Notion-main/main.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
