### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by linlithgowshire** [tsinglinrain/WechatPay_to_Notion#2]
运行代码时提示错误 
File "/Users/linlithgowshire/Downloads/WechatPay_to_Notion-main/main.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by linlithgowshire** [comment]
<img width="842" alt="截屏2024-06-27 22 48 23" src="https://github.com/tsinglinrain/WechatPay_to_Notion/assets/50478220/1919ead6-10ea-42e4-9087-1f68fe361e83">

**Comment by tsinglinrain** [comment]
因为这个库没安装，需要`pip install PyYAML`，其他的类似方法安装，比如pandas
另外linux环境下，需要在代码文件最前面添加`#!/usr/bin/python`

不过，我写了新版本的导入代码，整合了微信和支付宝账单导入，但是还没来及写说明书。而且最近比较忙，可能来不及发。可以实现账单发到邮箱，自己发密码，然后运行代码，就能导入。pre-release里面写了一部分代码，你可以看一看。

**Comment by tsinglinrain** [comment]
发了个beta分支，可以下载那个分支，但是没有写操作说明，可先自行查看。
