### ISSUE TITLE
解压密码错误

### ISSUE THREAD

**Issue by xchyyb** [tsinglinrain/WechatPay_to_Notion#4]
运行过程中提示解压密码错误，但已确认过没有问题，并且账单也已下载并通过密码解压成功
![image](https://github.com/user-attachments/assets/102d2a02-d627-4f6a-ac01-38609a26fd41)

**Comment by tsinglinrain** [comment]
从你的截图来看，账单csv文件是不需要密码的。你可以详细说一下你的使用流程，有改动过哪些东西吗？

**Comment by xchyyb** [comment]
谢谢回复，我除了改过config_private.yaml的信息外其他都没有做过修改，attachment文件夹中也有下载下来的压缩文件，但bill_csv_raw中没有账单csv文件，应该还是解压这一步出了问题。我也换了一个邮箱试过了，还是会出现这个错误。

> 从你的截图来看，账单csv文件是不需要密码的。你可以详细说一下你的使用流程，有改动过哪些东西吗？

**Comment by tsinglinrain** [comment]
不知道什么问题。希望你可以把命令行的全部打印内容截图贴过来（邮箱下载连接等隐私请打码）。打印内容应该是包括代码中设置的一些信息的，只截取一部分，我不知道问题所在。

![image](https://github.com/user-attachments/assets/49d4f326-8772-4689-940b-3d6c9068c173)
